# ignores known and problematic files, per rule.
# "problematic" files can be test files, mock data files and so on.
KEYS001:
    - .*secrets/rsa/rsa.key*
SENF005:
    - .*ipython_security.asc*
CLD001:
    - .*spectral-goat\src\frontend\fb.json*
AWS001:
    - .*create-react-context/.*
CLD001:
    - .src/frontend/fb.json
CLD001:
    - .*src/frontend/fb.json*
